{
 "title": "Cloudflare Analytics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Domain",
    "query": "SHOW TAG VALUES from \"cloudflare\".\"autogen\".\"cloudflare_analytics\" WITH KEY = \"zone\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total Number of Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "requests_all" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Countries Traffic Map",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 3, "w": 14, "x": 5, "y": 0 },
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics_access_by_country",
     "select": [
      [
       { "params": [ "visit_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Threats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"threats_all\") FROM \"cloudflare_analytics\" WHERE (\"zone\" =~ /^$Domain$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Countries Traffic Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 14, "x": 5, "y": 3 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics_access_by_country",
     "select": [
      [
       { "params": [ "visit_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT mean(\"bandwidth_all\") FROM \"cloudflare_analytics\" WHERE (\"zone\" =~ /^$Domain$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bandwidth_all" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Domain$/",
     "query": "SELECT mean(\"unique_all\") FROM \"cloudflare_analytics\" WHERE (\"zone\" =~ /^$Domain$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "result_totals_requests_cached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Cached Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "requests_all" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Domain$/",
     "query": "SELECT mean(\"bandwidth_cached\") FROM \"cloudflare_analytics\" WHERE (\"zone\" =~ /^$Domain$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "result_totals_requests_cached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status Code Counter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_http_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "http_status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics_http_status_by_zone",
     "select": [
      [
       { "params": [ "status_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Cached Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "bandwidth_cached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cached Requests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    },
    {
     "alias": "Uncached Bandwidth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "query": "SELECT last(\"visits\") FROM \"cloudflare_analytics_country\" WHERE $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "bandwidth_uncached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uncached Requests" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"requests_all\") FROM \"cloudflare_analytics\" WHERE (\"zone\" =~ /^$Domain$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "bandwidth_all" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "bandwidth_cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Uncached Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "requests_unchached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "requests_cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  },
  {
   "title": "Cached Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cloudflare_analytics",
     "select": [
      [
       { "params": [ "bandwidth_cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=~", "value": "/^$Domain$/" }
     ]
    }
   ]
  }
 ]
}